### PR TITLE
Starting to try to add bigger colliders in front of punches and kicks…

### PR DESCRIPTION
**Pull request by packerbacker8**
… to hit more area. Problem though with fists where colliders start below ground so get stuck.  Need a way for them to stay above ground and rotate to correct position during animation.

### CODE REVIEW

**Comment by kucab2345** [comment]
I am getting Null reference exceptions to line 152, 154 in PunchScript.cs. I think the colliders for the characters in the Cube Attack Script are missing in the prefabs perhaps? For example, Left Fist Collider, Right Fist Collider, etc are all empty in Cube Attack Script. What should they be exactly?

**Comment by kucab2345** [comment]
Yea, I think that's the problem. I dragged in the respective limbs from the PuppetMaster child object of the character and that seems to have fixed it.

**Comment by kucab2345** [comment]
I made a new commit that should resolve the problem. Chandler, can you make sure this doesn't break anything on your end. Alyssa, can you pull and confirm that nothing is problematic on your end, specifically - no null ref exceptions in PunchScript?

**Review by kucab2345 — DISMISSED** [review]
See my followup commit

**Comment by packerbacker8** [comment]
Added to prefabs the colliders needed to prevent null refs. They are not necessarily placed properly or the right size or place, but it is the start.

**Review by kucab2345 — APPROVED** [review]
Dis iz de wei.

**Pull request merged**
