### PR TITLE
Controller fix

### PR DESCRIPTION
**Pull request by JunoK95**
Controller Implemented for Combat and for Octahedron Character

### CODE REVIEW

**Comment by packerbacker8** [comment]
I will review these changes tomorrow and see how they feel.

**Review by kucab2345 — CHANGES_REQUESTED** [review]
Great start so far! You will need to merge with the new Master branch in order to get the latest changes. Some problems that I've noticed:

- You can not jump when you turn into cube form for the cubeman. 
- Turning into the cubeman is done w the X button, and turning into the octohedron special is done w the B button. These should be on the same button; pick one of the two and stick with it. 
- Hook attack is not mapped. Reach out to me or Chandler on this; I think the keycode for it is named wrong on our end.

**Comment by JunoK95** [comment]
Renew pull request.  Added new controller implementations for this branch

**Review by kucab2345 — DISMISSED** [review]

**Review by packerbacker8 — APPROVED** [review]
Henry fixed this merge conflict.

**Pull request merged**
